ServerName localhost
# MPM
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
# Authorization
LoadModule authz_core_module modules/mod_authz_core.so
# Proxy
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
# Logging
LoadModule log_config_module modules/mod_log_config.so
Listen 80

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined
LogLevel debug

<VirtualHost *:80>
    ProxyPreserveHost On
    # API
    ProxyPass /api/ http://api:8000/api/
    ProxyPassReverse /api/ http://api:8000/api/
    # WebSocket
    ProxyPass /ws/ ws://api:8000/ws/
    ProxyPassReverse /ws/ ws://api:8000/ws/
</VirtualHost>
